version: '3.8'

services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8081:8081"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
    command: sleep infinity
